export const SET_CONFIRMED = 'SET_CONFIRMED'
export const SET_RECOVERED = 'SET_RECOVERED'
export const SET_DEATH = 'SET_DEATH'
export const SET_DATE = 'SET_DATE'
export const SET_GLOBAL_LOADING = 'SET_GLOBAL_LOADING'

export const SET_LOCAL_CONFIRMED = 'SET_LOCAL_CONFIRMED'
export const SET_LOCAL_RECOVERED = 'SET_LOCAL_RECOVERED'
export const SET_LOCAL_DEATH = 'SET_LOCAL_DEATH'
export const SET_LOCAL_LOADING = 'SET_LOCAL_LOADING'

export const SET_LIST = 'SET_LIST'
export const SET_LIST_LOADING = 'SET_LIST_LOADING'


